[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.76"
bitflags = "2.4.1"
bytemuck = "1.14.0"
byteorder = "1.5.0"
glam = "0.25.0"
thiserror = "1.0.51"
winit = "0.28.0"
