[package]
name = "mtt"
version = "0.1.0+5.5.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
bitflags = "1.3.2"
bytemuck = { version = "1.7.2", features = ["derive"] }
byteorder = "1.4.3"
env_logger = { version = "0.9.0", default-features = false }
flate2 = "1.0.22"
log = "0.4.14"
mtt_macros = { path = "../mtt_macros" }
sha2 = "0.9.8"
shaderc = "0.7.3"
srp = { git = "https://github.com/weqqr/PAKEs", branch = "hn_xor_hg_fix" }
thiserror = "1.0.29"
tokio = { version = "1.12.0", features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
wgpu = { version = "0.11", features = ["spirv"] }
winit = "0.25.0"
zstd = "0.9.0"
