[package]
name = "mtt"
version = "0.1.0+5.5.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
byteorder = "1.4.3"
thiserror = "1.0.29"
wgpu = "0.11"
winit = "0.25.0"
mtt_macros = { path = "../mtt_macros" }
tokio = { version = "1.12.0", features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
srp =  { git = "https://github.com/weqqr/PAKEs", branch = "hn_xor_hg_fix" }
sha2 = "0.9.8"
log = "0.4.14"
env_logger = "0.9.0"
