[package]
name = "mtt_serialize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
byteorder = { workspace = true }
glam = { workspace = true }

[lints]
workspace = true
